language: python
dist: focal
python:
  - "3.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install 

install:

  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo pytz pymongo python-telegram-bot pyTelegramBotAPI certifi pytz

script:

  - chmod +x * && lscpu && python3 LEGEND.py